export default{
    houseKeeping:require('../../assets/categories/houseKeeping.png'),
    cook:require('../../assets/categories/cooking.png'),
    tailoring:require('../../assets/categories/tailoring.png'),
    plumber:require('../../assets/categories/plumber.png'),
    electician:require('../../assets/categories/electrician.png'),
    barber:require('../../assets/categories/barber.png'),
    beautician:require('../../assets/categories/beautician.png'),
    elderlyCare:require('../../assets/categories/elderlyCare.png'),
    carpenter:require('../../assets/categories/carpenter.png'),
    movers:require('../../assets/categories/movers.png'),
    painter:require('../../assets/categories/painter.png'),
    driver:require('../../assets/categories/driver.png'),
    photographer:require('../../assets/categories/photographer.png'),
    tutor:require('../../assets/categories/tutor.png'),
    hvacr:require('../../assets/categories/hvacr.png'),
    placeHolder: require('../../assets/placeHolder.png'),
}