export default {
  SPLASH_LOGO: require('../../../assets/images/logo.png'),
  GETSTARTED_IMAGE: require('../../../assets/images/background.jpg'),
  HEADER_LOGO: require('../../../assets/images/headerlogo.png'),
  ONBOARDING1_IMAGE: require('../../../assets/images/shopping2.png'),
  ONBOARDING2_IMAGE: require('../../../assets/images/shopping5.png'),
  ONBOARDING3_IMAGE: require('../../../assets/images/shopping11.png'),
  BACKCOVER_IMAGE: require('../../../assets/images/back2.png'),
  MORE_IMAGE: require('../../../assets/images/more.png'),
  GOBACK_IMAGE: require('../../../assets/images/less.png'),
  CART_IMAGE: require('../../../assets/images/cart.png'),
  SEARCH_IMAGE: require('../../../assets/images/search.png'),
  WISHLIST_IMAGE: require('../../../assets/images/heart.png'),
  DASHBOARD_IMAGE: require('../../../assets/images/walletbelt.png'),
  MENU: require('../../../assets/images/menu.png'),
  BAG_IMAGE: require('../../../assets/images/bag.png'),
  NO_ORDER: require('../../../assets/images/orders.png'),
  CARTIMAGE: require('../../../assets/images/carticon.png'),
  WISHLIST_LOGO: require('../../../assets/images/carticon.png'),
  NOT_FOUND: require('../../../assets/images/nofound.png'),
  CALL_US: require('../../../assets/images/call.png'),
  DEFAULT_ICON:require('../../../assets/images/app-icon.png'),
  DELETE: require('../../../assets/images/delete.png'),
  NO_INTERNET: require('../../../assets/images/nointernet.png'),
  EMAIL_US: require('../../../assets/images/emailicon.png'),
  LOCATION: require('../../../assets/images/location.png'),
  CLOSE: require('../../../assets/images/close.png'),
  EDIT: require('../../../assets/images/pen.png'),
  SORT: require('../../../assets/images/sort.png'),
  FILTER: require('../../../assets/images/filter.png'),
  COLLECTION_BG: require('../../../assets/images/2.png'),

  NEW_ARRIVALS: require('../../../assets/images/new_arrivals.jpg'),
  MEN_COLLECTION: require('../../../assets/images/men_collection.png'),
  WOMEN_COLLECTION: require('../../../assets/images/women_collection.jpg'),
  BOYS_COLLECTION: require('../../../assets/images/boys_collection.jpg'),
  GIRLS_COLLECTION: require('../../../assets/images/girls_collection.jpg'),
  KIDS_COLLECTION: require('../../../assets/images/kids_collection.jpg'),
  TOPS_SHIRTS_FOR_MEN: require('../../../assets/images/tops-shirts-for-men.jpg'),
  JEANS_TROUSERS_FOR_MEN: require('../../../assets/images/jeans-trousers-shorts-for-men.jpg'),
  BOXERS_TRACKSUITS_FOR_MEN: require('../../../assets/images/boxers-track-suits-for-men.jpg'),
  ACCESSORIES: require('../../../assets/images/accessories.jpg'),
  TOPS_SHIRTS_FOR_WOMEN: require('../../../assets/images/tops-shirts-for-women.jpg'),
  JEANS_TROUSERS_FOR_WOMEN: require('../../../assets/images/jeans-trousers-pants-for-women.jpg'),
  SALE: require('../../../assets/images/sale.jpg'),
  DROPDOWN_ICON:require('../../../assets/images/down.png'),
  NEW_ARRIVALS1: require('../../../assets/images/new-arrivals1.jpg'),
  MEN_COLLECTION1: require('../../../assets/images/men-collection1.jpg'),
  WOMEN_COLLECTION1: require('../../../assets/images/women-collection1.jpg'),
  BOYS_COLLECTION1: require('../../../assets/images/boys-collection1.jpg'),
  GIRLS_COLLECTION1: require('../../../assets/images/girls-collection1.jpg'),
  KIDS_COLLECTION1: require('../../../assets/images/kids-collection1.jpg'),
  SALE1: require('../../../assets/images/sale1.jpg'),
  ACCESSORIES1: require('../../../assets/images/accessories1.jpg'),
  BOXERS_TRACKSUITS_FOR_MEN1: require('../../../assets/images/boxers-track-suits-for-men1.png'),
  FAVOURITE: 'favorite',
};
